### ISSUE TITLE
Renderer crash

### ISSUE THREAD

**Issue by sigaloid** [rooklift/nibbler#227]
> The renderer process has crashed. Experience suggests this happens when Leela runs out of RAM. If this doesn't apply, please tell the author how you made it happen

Might be because of a lack of VRAM, but I've got 64GB of RAM and it's nowhere near full when I get this message. Installed from [AUR](https://aur.archlinux.org/packages/nibbler-git), has happened twice but both times my memory was fine (less than 1/32th full). 

Arch latest

**Comment by rooklift** [comment]
Hmm - mysterious.

**Comment by whelanh** [comment]
I am getting the same on Ubuntu 23.04.  I am running it directly from the files/src directory using "electron ."  Maybe it's a GPU config issue?  I am attaching  my inxi file below.  Error message was:
[inxi.txt](https://github.com/rooklift/nibbler/files/12352128/inxi.txt)
[inxi.txt](https://github.com/rooklift/nibbler/files/12352131/inxi.txt)

[13237:0815/143703.136999:ERROR:gl_surface_presentation_helper.cc(260)] GetVSyncParametersIfAvailable() failed for 1 times!
[13237:0815/143703.142280:ERROR:gl_surface_presentation_helper.cc(260)] GetVSyncParametersIfAvailable() failed for 2 times!
Error sending from webFrameMain:  Error: Render frame was disposed before WebFrameMain could be accessed
    at WebFrameMain.send (node:electron/js2c/browser_init:2:94361)
    at WebContents.send (node:electron/js2c/browser_init:2:79721)
    at click (/home/hugh/Downloads/nibbler/files/src/main.js:3994:23)
    at MenuItem.click (node:electron/js2c/browser_init:2:30958)
    at Menu._executeCommand (node:electron/js2c/browser_init:2:36354)
[13237:0815/143706.115012:ERROR:gl_surface_presentation_helper.cc(260)] GetVSyncParametersIfAvailable() failed for 3 times!
Error sending from webFrameMain:  Error: Render frame was disposed before WebFrameMain could be accessed
    at WebFrameMain.send (node:electron/js2c/browser_init:2:94361)
    at WebContents.send (node:electron/js2c/browser_init:2:79721)
    at BrowserWindow.<anonymous> (/home/hugh/Downloads/nibbler/files/src/main.js:121:21)
    at BrowserWindow.emit (node:events:513:28)
    at appMethod (node:electron/js2c/browser_init:2:24945)
    at Object.execute (node:electron/js2c/browser_init:2:29083)
    at MenuItem.click (node:electron/js2c/browser_init:2:30912)
    at Menu._executeCommand (node:electron/js2c/browser_init:2:36354)
Renderer seems unresponsive, quitting anyway.

**Comment by whelanh** [comment]
For anyone else who got the error message (see my comment above) while running nibbler using "electron ." from the github files/src directory, I was able to get nibbler to run by simply using the Linux install script from the GitHub page and then running nibbler using "nibbler --no-sandbox" from the terminal as mentioned by rooklift in #203.  This is not my issue, but I would consider closed if the goal is simply to get nibbler running on linux and a hybrid gpu laptop system.

**Comment by mgarraha** [comment]
My workaround is to put this in $HOME/.config/Nibbler/config.json:

        "disable_hw_accel": true,

**Comment by TimJentzsch** [comment]
I had a similar problem, I got:

```
[38735:0121/215043.645240:FATAL:gpu_data_manager_impl_private.cc(439)] GPU process isn't usable. Goodbye.
[1]    38735 trace trap (core dumped)  /usr/local/bin/nibbler
```
both with the app downloaded from GitHub releases and with the install script.

But the fix with `nibbler --no-sandbox` worked, thank you!
